apiVersion: apps/v1
kind: Deployment
metadata:
  name: deakin-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deakin-frontend
  template:
    metadata:
      labels:
        app: deakin-frontend
    spec:
      containers:
        - name: deakin-frontend
          image: shichengxiang/deakin-frontend:v13
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: deakin-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: deakin-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
