apiVersion: apps/v1
kind: Deployment
metadata:
  name: deakin-marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deakin-marketplace
  template:
    metadata:
      labels:
        app: deakin-marketplace
    spec:
      containers:
        - name: deakin-backend
          image: shichengxiang/deakin-marketplace:v5
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MONGODB_URI
              value: "mongodb+srv://s224387468:2xyT400NMy7R4M7p@cluster0.dzxhohq.mongodb.net/deakin-marketplace?retryWrites=true&w=majority"
          volumeMounts:
            - name: uploads-volume
              mountPath: /app/uploads
      volumes:
        - name: uploads-volume
          emptyDir: {}
