# Dockerfile-backend
FROM node:18

WORKDIR /app

# Copy all back-end files
COPY server/ ./server/
COPY uploads/ ./uploads/
COPY package*.json ./


RUN npm install

# port
EXPOSE 5000

# start server
CMD ["node", "server/index.js"]
