apiVersion: v1
kind: Service
metadata:
  name: deakin-marketplace-service
spec:
  type: LoadBalancer
  selector:
    app: deakin-marketplace
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
